# Generated by Django 6.0.3 on 2026-03-15 10:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_auto_20200306_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='장비 이름')),
                ('description', models.TextField(blank=True, verbose_name='장비 설명')),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='room_type',
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성 일시'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room_date',
            field=models.DateField(max_length=20, verbose_name='예약 날짜'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room_finish_time',
            field=models.FloatField(verbose_name='종료 시간 (0-24)'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room_start_time',
            field=models.FloatField(verbose_name='시작 시간 (0-24)'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.CharField(max_length=10, verbose_name='예약자 학번/이름'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.equipment', verbose_name='예약 장비'),
        ),
    ]
